use anyhow::{Context, Result};
use serde::{Deserialize, Serialize};
use std::collections::HashMap;
use std::path::PathBuf;

/// Built-in profiles. "linux" can be overridden via DISTQ_REPOS env var.
pub fn builtin_profiles() -> HashMap<&'static str, Vec<&'static str>> {
    let mut m = HashMap::new();
    m.insert(
        "linux",
        vec![
            "arch",
            "debian_unstable",
            "fedora_rawhide",
            "ubuntu_24_04",
            "alpine_edge",
            "nixos",
            "gentoo",
            "void_x86_64",
        ],
    );
    m.insert(
        "bsd",
        vec!["freebsd", "openbsd", "pkgsrc_current", "homebrew"],
    );
    m.insert(
        "all",
        vec![
            "arch",
            "debian_unstable",
            "fedora_rawhide",
            "ubuntu_24_04",
            "alpine_edge",
            "nixos",
            "gentoo",
            "void_x86_64",
            "freebsd",
            "openbsd",
            "pkgsrc_current",
        ],
    );
    m
}

#[derive(Debug, Deserialize, Serialize, Default)]
pub struct Config {
    /// User-defined profiles: profile name → list of repo identifiers.
    #[serde(default)]
    pub profiles: HashMap<String, Vec<String>>,

    /// Default repos used when neither --repos, --profile, --repo, nor DISTQ_REPOS is set.
    /// If absent, falls back to autodetect.
    #[serde(default)]
    pub default_repos: Vec<String>,

    /// Ordered list of source backends to try.
    /// Each repo is routed to the first source in this list that supports it.
    /// Available: "docker", "arch", "aur", "fedora", "alpine", "debian", "ubuntu", "nixos", "repology"
    /// repology is always appended as last-resort fallback even if omitted.
    #[serde(default)]
    pub source_priority: Vec<String>,

    /// Docker source settings.
    #[serde(default)]
    pub docker: DockerConfig,
}

#[derive(Debug, Deserialize, Serialize, Default)]
pub struct DockerConfig {
    /// Directory to search for Dockerfile.<distro> files when building images.
    /// Defaults to: directory next to the distq binary, then ~/.config/distq/dockerfiles/
    pub dockerfiles_dir: Option<PathBuf>,
}

impl Config {
    pub fn load() -> Result<Self> {
        let path = config_path();
        if !path.exists() {
            return Ok(Self::default());
        }
        let text = std::fs::read_to_string(&path)
            .with_context(|| format!("reading {}", path.display()))?;
        toml::from_str(&text)
            .with_context(|| format!("parsing {}", path.display()))
    }

    /// Resolve a named profile to a list of repo strings.
    /// Priority: user config profiles > built-in profiles.
    pub fn resolve_profile<'a>(&'a self, name: &str) -> Option<Vec<String>> {
        if let Some(repos) = self.profiles.get(name) {
            return Some(repos.clone());
        }
        let builtins = builtin_profiles();
        builtins
            .get(name)
            .map(|repos| repos.iter().map(|r| r.to_string()).collect())
    }
}

pub fn config_path() -> PathBuf {
    dirs_next::config_dir()
        .unwrap_or_else(|| PathBuf::from("~/.config"))
        .join("distq")
        .join("config.toml")
}

pub fn write_default_config() -> anyhow::Result<()> {
    let path = config_path();
    if path.exists() {
        anyhow::bail!(
            "config already exists: {}\nRemove it first if you want to regenerate.",
            path.display()
        );
    }
    if let Some(dir) = path.parent() {
        std::fs::create_dir_all(dir)
            .with_context(|| format!("creating {}", dir.display()))?;
    }

    let content = r#"# distq configuration
# Generated by: distq --init-config

# ── Default repos ─────────────────────────────────────────────────────────────
# Used when no --repo/--repos/--profile is given and autodetect fails.
# Uncomment and edit to set your preferred repos:
#
# default_repos = ["arch", "debian_unstable", "fedora_rawhide"]

# ── Source priority ───────────────────────────────────────────────────────────
# Order in which backends are tried for each repo.
# First source whose supports(repo) returns true wins.
# "repology" is always appended as last-resort fallback even if omitted here.
#
# Available sources: docker, arch, aur, fedora, alpine, debian, ubuntu, nixos, repology
# docker uses local distq/<distro> images (offline, no rate limits) — recommended first.
#
[sources]
priority = ["docker", "arch", "aur", "fedora", "alpine", "debian", "ubuntu", "nixos", "repology"]

# ── Docker ────────────────────────────────────────────────────────────────────
# Settings for the docker source and `distq docker build`.
#
# dockerfiles_dir: where to look for Dockerfile.<distro> files.
# Default search order: next to the binary → ~/.config/distq/dockerfiles/
#
# [docker]
# dockerfiles_dir = "/home/user/projects/distros-search/dockerfiles"

# ── Profiles ──────────────────────────────────────────────────────────────────
# Named repo groups. Use with: distq --profile <name> <package>
# Built-in profiles (can be overridden here): linux, bsd, all
#
[profiles]
# linux   = ["arch", "debian_unstable", "fedora_rawhide", "ubuntu_24_04", "alpine_edge", "nixos", "gentoo", "void_x86_64"]
# bsd     = ["freebsd", "openbsd", "pkgsrc_current", "homebrew"]
# mystack = ["arch", "alpine_edge", "nixos"]
"#;

    std::fs::write(&path, content)
        .with_context(|| format!("writing {}", path.display()))?;
    println!("distq: config written to {}", path.display());
    Ok(())
}

/// Resolve the directory that contains `Dockerfile.*` files for `distq docker build`.
///
/// Search order:
///   1. `config.docker.dockerfiles_dir` if set
///   2. Directory containing the current executable
///   3. `~/.config/distq/dockerfiles/`
///
/// Returns the first directory that exists and contains at least one `Dockerfile.*`.
pub fn resolve_dockerfiles_dir(cfg: &Config) -> Option<PathBuf> {
    let candidates: Vec<PathBuf> = {
        let mut v = Vec::new();
        if let Some(ref p) = cfg.docker.dockerfiles_dir {
            v.push(p.clone());
        }
        if let Ok(exe) = std::env::current_exe() {
            if let Some(dir) = exe.parent() {
                v.push(dir.to_path_buf());
            }
        }
        v.push(
            dirs_next::config_dir()
                .unwrap_or_else(|| PathBuf::from("~/.config"))
                .join("distq")
                .join("dockerfiles"),
        );
        v
    };

    candidates.into_iter().find(|dir| {
        dir.exists()
            && std::fs::read_dir(dir)
                .ok()
                .map(|mut d| {
                    d.any(|e| {
                        e.ok()
                            .and_then(|e| e.file_name().into_string().ok())
                            .map(|n| n.starts_with("Dockerfile."))
                            .unwrap_or(false)
                    })
                })
                .unwrap_or(false)
    })
}

/// Parse a comma-separated list of repo names, normalizing each one.
pub fn parse_repos(s: &str) -> Vec<String> {
    s.split(',')
        .map(str::trim)
        .filter(|s| !s.is_empty())
        .map(|r| crate::normalize_repo(r.to_string()))
        .collect()
}
